import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
  sarasa,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
  sarasa: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
          {modal}
          {sarasa}
        </main>
      </body>
    </html>
  );
}
